export const GET_CURRENT = 'GET_CURRENT';
export const GET_DAILY = 'GET_DAILY';
export const GET_CITY = 'GET_CITY';
export const GET_BY_LOCATION_CURRENT = 'GET_BY_LOCATION_CURRENT';
export const GET_BY_LOCATION_DAILY = 'GET_BY_LOCATION_DAILY';
